# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Design System Template
author: Lundegaard a.s.
email: design-systems@lundegaard.eu
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://designmanual.sagebionetworks.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-redirect-from

sass:
  style: compressed

# Setup pattern collection
collections:
  patterns:
    output: true
  posts:
    output: true
    permalink: /release-history/:year/:month/:day/:title/

# Configure minification
jekyll-minifier:
  exclude: ['*.html', '*.xml', '*.txt']  # Exclude xml and html files from processing (take too long to generate)

# If you want use Lundegaard design-system-template as jekyll theme. For more
# info see https://github.com/lundegaard/design-system-template/wiki/Instalation/

# remote_theme: lundegaard/design-system-template  # you can specify git branch or commit lundegaard/design-system-template@v0.1.0

# Overriding default colors
branding:
  logo_path: '/assets/logo.svg'
  navigation_background_color: '#eee'
  navigation_link_color: '#444'
  navigation_link_color_hover: 'gray'
  main_background_color: '#fff'
  highlight_color: '#444'
  code_background_color: '#f9f9f9'
  
# GTM analytics
gtm_id: GTM-XXXXXX
